# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/glossary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/glossary.proto\x12\x08glossary\x1a\x1bgoogle/protobuf/empty.proto\"o\n\x04Term\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07keyword\x18\x02 \x01(\t\x12\x12\n\ndefinition\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x12\n\nupdated_at\x18\x06 \x01(\t\")\n\x08TermList\x12\x1d\n\x05terms\x18\x01 \x03(\x0b\x32\x0e.glossary.Term\"&\n\x13GetByKeywordRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"\x1c\n\x0eGetByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"H\n\x11\x43reateTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x12\n\ndefinition\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\"T\n\x11UpdateTermRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07keyword\x18\x02 \x01(\t\x12\x12\n\ndefinition\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\"\x1f\n\x11\x44\x65leteTermRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xf8\x02\n\x08Glossary\x12\x37\n\tListTerms\x12\x16.google.protobuf.Empty\x1a\x12.glossary.TermList\x12\x41\n\x10GetTermByKeyword\x12\x1d.glossary.GetByKeywordRequest\x1a\x0e.glossary.Term\x12\x37\n\x0bGetTermById\x12\x18.glossary.GetByIdRequest\x1a\x0e.glossary.Term\x12\x39\n\nCreateTerm\x12\x1b.glossary.CreateTermRequest\x1a\x0e.glossary.Term\x12\x39\n\nUpdateTerm\x12\x1b.glossary.UpdateTermRequest\x1a\x0e.glossary.Term\x12\x41\n\nDeleteTerm\x12\x1b.glossary.DeleteTermRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TERM']._serialized_start=63
  _globals['_TERM']._serialized_end=174
  _globals['_TERMLIST']._serialized_start=176
  _globals['_TERMLIST']._serialized_end=217
  _globals['_GETBYKEYWORDREQUEST']._serialized_start=219
  _globals['_GETBYKEYWORDREQUEST']._serialized_end=257
  _globals['_GETBYIDREQUEST']._serialized_start=259
  _globals['_GETBYIDREQUEST']._serialized_end=287
  _globals['_CREATETERMREQUEST']._serialized_start=289
  _globals['_CREATETERMREQUEST']._serialized_end=361
  _globals['_UPDATETERMREQUEST']._serialized_start=363
  _globals['_UPDATETERMREQUEST']._serialized_end=447
  _globals['_DELETETERMREQUEST']._serialized_start=449
  _globals['_DELETETERMREQUEST']._serialized_end=480
  _globals['_GLOSSARY']._serialized_start=483
  _globals['_GLOSSARY']._serialized_end=859
# @@protoc_insertion_point(module_scope)
