# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import glossary_pb2 as proto_dot_glossary__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/glossary_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GlossaryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTerms = channel.unary_unary(
                '/glossary.Glossary/ListTerms',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_glossary__pb2.TermList.FromString,
                _registered_method=True)
        self.GetTermByKeyword = channel.unary_unary(
                '/glossary.Glossary/GetTermByKeyword',
                request_serializer=proto_dot_glossary__pb2.GetByKeywordRequest.SerializeToString,
                response_deserializer=proto_dot_glossary__pb2.Term.FromString,
                _registered_method=True)
        self.GetTermById = channel.unary_unary(
                '/glossary.Glossary/GetTermById',
                request_serializer=proto_dot_glossary__pb2.GetByIdRequest.SerializeToString,
                response_deserializer=proto_dot_glossary__pb2.Term.FromString,
                _registered_method=True)
        self.CreateTerm = channel.unary_unary(
                '/glossary.Glossary/CreateTerm',
                request_serializer=proto_dot_glossary__pb2.CreateTermRequest.SerializeToString,
                response_deserializer=proto_dot_glossary__pb2.Term.FromString,
                _registered_method=True)
        self.UpdateTerm = channel.unary_unary(
                '/glossary.Glossary/UpdateTerm',
                request_serializer=proto_dot_glossary__pb2.UpdateTermRequest.SerializeToString,
                response_deserializer=proto_dot_glossary__pb2.Term.FromString,
                _registered_method=True)
        self.DeleteTerm = channel.unary_unary(
                '/glossary.Glossary/DeleteTerm',
                request_serializer=proto_dot_glossary__pb2.DeleteTermRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class GlossaryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListTerms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTermByKeyword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTermById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GlossaryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTerms': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTerms,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_glossary__pb2.TermList.SerializeToString,
            ),
            'GetTermByKeyword': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTermByKeyword,
                    request_deserializer=proto_dot_glossary__pb2.GetByKeywordRequest.FromString,
                    response_serializer=proto_dot_glossary__pb2.Term.SerializeToString,
            ),
            'GetTermById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTermById,
                    request_deserializer=proto_dot_glossary__pb2.GetByIdRequest.FromString,
                    response_serializer=proto_dot_glossary__pb2.Term.SerializeToString,
            ),
            'CreateTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTerm,
                    request_deserializer=proto_dot_glossary__pb2.CreateTermRequest.FromString,
                    response_serializer=proto_dot_glossary__pb2.Term.SerializeToString,
            ),
            'UpdateTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTerm,
                    request_deserializer=proto_dot_glossary__pb2.UpdateTermRequest.FromString,
                    response_serializer=proto_dot_glossary__pb2.Term.SerializeToString,
            ),
            'DeleteTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTerm,
                    request_deserializer=proto_dot_glossary__pb2.DeleteTermRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'glossary.Glossary', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('glossary.Glossary', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Glossary(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTerms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.Glossary/ListTerms',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_glossary__pb2.TermList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTermByKeyword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.Glossary/GetTermByKeyword',
            proto_dot_glossary__pb2.GetByKeywordRequest.SerializeToString,
            proto_dot_glossary__pb2.Term.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTermById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.Glossary/GetTermById',
            proto_dot_glossary__pb2.GetByIdRequest.SerializeToString,
            proto_dot_glossary__pb2.Term.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.Glossary/CreateTerm',
            proto_dot_glossary__pb2.CreateTermRequest.SerializeToString,
            proto_dot_glossary__pb2.Term.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.Glossary/UpdateTerm',
            proto_dot_glossary__pb2.UpdateTermRequest.SerializeToString,
            proto_dot_glossary__pb2.Term.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.Glossary/DeleteTerm',
            proto_dot_glossary__pb2.DeleteTermRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
